- type: job
  Contractor
  name: job-name-contractor
  description: job-description-contractor
  playTimeTracker: DSJobPassenger
  salary: 6000
  requirements: #Lua
    - !type:OverallPlaytimeRequirement
      time: 72000
  icon: "JobIconContractor"
  supervisors: job-supervisors-hire
  displayWeight: 20
  accessGroups:
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: chameleonOutfit
  ContractorChameleonOutfit
  job: DSContractor
