- type: job
  id: DSContractor
  name: Гражданский
  description: Я еблан, занимаюсь какой-то хуйней, я не знал, но люди мне так сказали
  playTimeTracker: DSJobPassenger
  salary: 6000
  requirements: #Lua
    - !type:OverallPlaytimeRequirement
      time: 72000
  icon: "JobIconContractor"
  supervisors: job-supervisors-hire
  displayWeight: 40
  accessGroups:
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: chameleonOutfit
  id: DSContractorChameleonOutfit
  job: DSContractor
