- type: job
  id: DSMercenary
  name: job-name-mercenary
  description: job-description-mercenary
  playTimeTracker: JobMercenary
  requirements:
    - !type:RoleTimeRequirement
      role: DSContractor
      time: 72000 #Lua 20h 
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 72000 #Lua 20h
    - !type:RoleTimeRequirement
      role: DSFrontierEngineer
      time: 72000 #Lua 20h 
    - !type:RoleTimeRequirement
      role: DSCadet
      time: 72000 #Lua 20h 
#    - !type:OverallPlaytimeRequirement
#      time: 108000
  startingGear: MercenaryGear
  canBeAntag: true
  icon: "JobIconMercenary"
  supervisors: job-supervisors-hire
  weight: 3 # Prioritize station & department jobs
  displayWeight: 20 # Second from the bottom
  setPreference: true
  access:
  - Mercenary
  accessGroups:
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: chameleonOutfit
  id: DSMercenaryChameleonOutfit
  job: Mercenary
  equipment:
    head: ClothingHeadHelmetMercenary
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGasMercenary
    neck: ClothingNeckIFFNeutral
    outerClothing: ClothingOuterVestWebMercenary
    gloves: ClothingHandsGlovesCombat
