- type: job
  Bailiff
  name: job-name-bailiff
  description: job-description-bailiff
  playTimeTracker: DSJobBailiff
  salary: 50000 #Lua 65000<50000
  requirements:
  - !type:RoleTimeRequirement #Lua
    role: DSJobSeniorOfficer
    time: 72000 # 10h
  startingGear: BailiffGear
  icon: JobIconBailiff
  supervisors: job-supervisors-sheriff
  weight: 150
  displayWeight: 60
  canBeAntag: false
  access:
  - Armory
  - Sergeant
  - Bailiff
  - Brigmedic
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Security

- type: chameleonOutfit
  BailiffChameleonOutfit
  job: DSBailiff
  hasMindShield: true
  equipment:
    head: ClothingHeadHatNfsdBeretBrown
    mask: ClothingMaskGasNfsd
    eyes: ClothingEyesGlassesNfsd
    outerClothing: ClothingOuterCoatNfsdFormal
    neck: ClothingNeckNfsdBadgeWarden
    belt: ClothingBeltNfsdFilled
    gloves: ClothingHandsGlovesCombatNfsdCream
    shoes: ClothingShoesBootsNfsdCreamFilled
