- type: job
  id: DSCadet
  name: job-name-cadet-nf
  description: job-description-cadet-nf
  playTimeTracker: DSJobSecurityCadet
  salary: 30000 #Lua 35000<30000
  requirements:
  - !type:RoleTimeRequirement #Lua
    role: DSPilot
    time: 72000 # 20h
#    - !type:OverallPlaytimeRequirement # comment from _Lua
#      time: 21600 # 6 hours
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 64800 # 18 hours
#      inverted: true # Leave slots open for newer, less confident players.
  startingGear: SDBaseLuaGear #Lua CadetGear<SDBaseLuaGear
  icon: JobIconCadetNF
  supervisors: job-supervisors-cadet
  weight: 70
  displayWeight: 10
  canBeAntag: false
  accessGroups:
  - CadetNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Security

- type: chameleonOutfit
  id: DSCadetChameleonOutfit
  job: DSCadet
  hasMindShield: true
  equipment:
    head: ClothingHeadHatNfsdBeretBrown
    mask: ClothingMaskGasNfsd
    eyes: ClothingEyesGlassesNfsd
    outerClothing: ClothingOuterArmorNfsd
    neck: ClothingNeckNfsdBadgeSecurityCadet
    belt: ClothingBeltNfsdFilled
    gloves: ClothingHandsGlovesCombatNfsdBrown
    shoes: ClothingShoesBootsNfsdBrownFilled

